import React from 'react';
import { Document, Page, Text, View, StyleSheet, Font } from '@react-pdf/renderer';
import { createTw } from 'react-pdf-tailwind';

// Need to register a Thai font for react-pdf to render Thai characters correctly
Font.register({
  family: 'Noto Sans Thai',
  src: 'https://cdn.jsdelivr.net/gh/lazywasabi/thai-web-fonts@7/fonts/NotoSansThai/NotoSansThai-Regular.ttf'
});

const tw = createTw({
  theme: {
    fontFamily: {
      sans: ['Noto Sans Thai'],
    },
    extend: {
      colors: {
        brand: '#2F5DFF',
      },
    },
  },
});

const styles = StyleSheet.create({
  page: {
    fontFamily: 'Noto Sans Thai',
    backgroundColor: '#ffffff',
    padding: 40,
  },
});

interface SalesReportDocumentProps {
  data: {
    salesTrend: any[];
    topProducts: any[];
    categoryDistribution: any[];
  };
  startDate: string;
  endDate: string;
}

export const SalesReportDocument = ({ data, startDate, endDate }: SalesReportDocumentProps) => {
  const totalRevenue = data.salesTrend.reduce((sum, item) => sum + Number(item.totalRevenue), 0);
  const totalOrders = data.salesTrend.reduce((sum, item) => sum + Number(item.totalOrders), 0);

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={tw('flex flex-row justify-between items-center mb-8 border-b-2 border-gray-800 pb-4')}>
          <View>
            <Text style={tw('text-3xl font-bold')}>MUSICGEAR</Text>
            <Text style={tw('text-gray-500 text-sm mt-1')}>Official Sales Report</Text>
          </View>
          <View style={tw('text-right')}>
            <Text style={tw('text-sm text-gray-500')}>Period</Text>
            <Text style={tw('text-sm font-bold')}>
              {new Date(startDate).toLocaleDateString('th-TH')} - {new Date(endDate).toLocaleDateString('th-TH')}
            </Text>
          </View>
        </View>

        {/* Summary KPIs */}
        <View style={tw('flex flex-row gap-4 mb-8')}>
          <View style={tw('flex-1 bg-gray-100 p-4 rounded-md')}>
            <Text style={tw('text-sm text-gray-500 mb-1')}>Total Revenue</Text>
            <Text style={tw('text-xl font-bold text-brand')}>
              {new Intl.NumberFormat('th-TH', { style: 'currency', currency: 'THB' }).format(totalRevenue)}
            </Text>
          </View>
          <View style={tw('flex-1 bg-gray-100 p-4 rounded-md')}>
            <Text style={tw('text-sm text-gray-500 mb-1')}>Total Orders</Text>
            <Text style={tw('text-xl font-bold')}>
              {totalOrders}
            </Text>
          </View>
        </View>

        {/* Top Products Table */}
        <View style={tw('mb-4')}>
          <Text style={tw('text-lg font-bold mb-4')}>Top Selling Products</Text>
          
          <View style={tw('flex flex-row border-b border-gray-300 pb-2 mb-2')}>
            <Text style={tw('flex-[3] text-sm font-bold text-gray-600')}>Product Name</Text>
            <Text style={tw('flex-1 text-sm font-bold text-gray-600')}>Category</Text>
            <Text style={tw('flex-1 text-sm font-bold text-gray-600 text-right')}>Qty</Text>
            <Text style={tw('flex-1 text-sm font-bold text-gray-600 text-right')}>Revenue</Text>
          </View>
          
          {data.topProducts.map((p, i) => (
            <View key={i} style={tw('flex flex-row py-2 border-b border-gray-100')}>
              <Text style={tw('flex-[3] text-sm')}>{p.productName}</Text>
              <Text style={tw('flex-1 text-sm')}>{p.category}</Text>
              <Text style={tw('flex-1 text-sm text-right')}>{p.quantitySold}</Text>
              <Text style={tw('flex-1 text-sm text-right')}>
                {new Intl.NumberFormat('th-TH').format(p.revenue)}
              </Text>
            </View>
          ))}
        </View>
        
        {/* Footer */}
        <View style={tw('absolute bottom-10 left-10 right-10 flex flex-row justify-between border-t border-gray-200 pt-4')}>
          <Text style={tw('text-xs text-gray-400')}>Generated by MusicGear Admin System</Text>
          <Text style={tw('text-xs text-gray-400')}>{new Date().toLocaleDateString('th-TH')}</Text>
        </View>

      </Page>
    </Document>
  );
};
